# https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script

- name: Install Docker
  shell: |
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sh /tmp/get-docker.sh
