db:
  image: mongo:latest
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles
  restart: always

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=http://localhost
    - Accounts_UseDNSDomainCheck=false
  links:
    - db:db
  ports:
    - 3000:3000
  restart: always

hubot:
  image: rocketchat/hubot-rocketchat:latest
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=general
    - ROCKETCHAT_USER=hubot
    - ROCKETCHAT_PASSWORD=hubot
    - BOT_NAME=hubot
    - HUBOT_RSS_INTERVAL=60
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-diagnostics,hubot-rss-reader
  links:
    - rocketchat:rocketchat
  ports:
    - 3001:8080
