# https://docs.rocket.chat/deploy/deploy-rocket.chat/deploy-with-docker-and-docker-compose#deploy-rocket.chat-on-docker
- name: Create application directory
  file: path={{ item }} state=directory
  with_items:
    - /opt/rocket.chat

- name: Copy docker-compose.yml
  copy: src=compose.yml dest=/opt/rocket.chat/compose.yml

- name: Start docker compose
  shell: docker compose up -d
  args:
    chdir: /opt/rocket.chat
